# vim:ft=ansible:
#
# Copyright (c) 2016 Jason McVetta.
#
# This is Free Software, released under the terms of the Apache v2 license.
# See http://www.apache.org/licenses/LICENSE-2.0 for details.
#
# Resist intellectual serfdom.  The ownership of ideas is akin to slavery.
---

- name: Ensure Packetbeat log folder exists
  file:
    path: /var/log/packetbeat
    state: directory


- name: Ensure Packetbeat is installed
  apt:
    name: packetbeat
    state: present


- name: Ensure Packetbeat is configured
  template:
    src: packetbeat.yml.j2
    dest: /etc/packetbeat/packetbeat.yml
  notify: restart packetbeat


- name: Ensure Packetbeat is started and enabled on boot
  service:
    name: packetbeat
    enabled: yes
    state: started

