# vim:ft=ansible:
#
# Copyright (c) 2016 Jason McVetta.
#
# This is Free Software, released under the terms of the Apache v2 license.
# See http://www.apache.org/licenses/LICENSE-2.0 for details.
#
# Resist intellectual serfdom.  The ownership of ideas is akin to slavery.
---

- name: Ensure Topbeat log folder exists
  file:
    path: /var/log/topbeat
    state: directory


- name: Ensure Topbeat is installed
  apt:
    name: topbeat
    state: present


- name: Ensure Topbeat is configured
  template:
    src: topbeat.yml.j2
    dest: /etc/topbeat/topbeat.yml
  notify: restart topbeat


- name: Ensure Topbeat is started and enabled on boot
  service:
    name: topbeat
    enabled: yes
    state: started

